### ISSUE TITLE
Case conversion issue

### ISSUE THREAD

**Issue by rybawdz** [chanced/caps#25]
Hi, from my assumptions, case convertion functions should always return the same output on particular input, i.e if we convert any letter to upper letter it should be the same as if we first converted it to lower and then to upper (correct me if I'm wrong).
However that is not he case for letters "ϴ" and "ẞ" and some other obscure inputs.

**Comment by chanced** [comment]
Can you please provide an example repro? This passes:

```go
func Test_Issue25(t *testing.T) {
	tests := []string{"ϴ", "ẞ"}
	for _, x := range tests {
		c := caps.NewConverter(caps.DefaultReplacements, caps.DefaultTokenizer, nil)
		lower := c.Convert(caps.ConvertRequest{
			Input:        x,
			ReplaceStyle: caps.ReplaceStyleLower,
		})

		upper := c.Convert(caps.ConvertRequest{
			Input:        lower,
			ReplaceStyle: caps.ReplaceStyleCamel,
		})

		if x != upper {
			t.Errorf("expected %s, got %s", x, upper)
		}
	}
}
```

**Comment by chanced** [comment]
Oops, one second. It has been a minute since I tested this. I just realized I didn't lower the lower. Checking.

**Comment by chanced** [comment]
There's definitely an issue, this fails:

```go
	tests := []string{"ϴ", "ẞ"}
	for _, x := range tests {
		c := caps.NewConverter(caps.DefaultReplacements, caps.DefaultTokenizer, nil)
		lower := c.Convert(caps.ConvertRequest{Input: x, Style: caps.StyleLower})

		upper := c.Convert(caps.ConvertRequest{
			Input: lower,
		})

		if x != upper {
			if unicode.ToTitle([]rune(x)[0]) == []rune(upper)[0] {
				t.Errorf("converted to title")
			}
			t.Errorf("expected %s, got %s", x, upper)
		}
	}
```

**Comment by chanced** [comment]
So this is a weird one. It's actually the `unicode` package that's causing the issue. I'm not sure if greek is a special case or not though.
```go
for _, x := range []string{"ϴ", "ẞ"} {
	l := unicode.ToLower([]rune(x)[0])
	u := unicode.ToUpper(l)
	fmt.Printf("%s: %s\n", x, string(u))
}
```

I don't know how to solve this if there isn't a [SpecialCase](https://pkg.go.dev/unicode#SpecialCase) for Greek. If there isn't a special case, this seems like it may be a bug in the unicode package. I'm not sure.

**Comment by chanced** [comment]
Here's the playground link: https://go.dev/play/p/QufWKeKAxwV

**Comment by chanced** [comment]
go issue: https://github.com/golang/go/issues/56448

**Comment by chanced** [comment]
From Rob Pike himself:

> There are multiple theta characters in Unicode, and I don't know what the right word is, but 1012 is U_3F4, which is not "canonical". It is a Unicode "symbol", not a letter. It's in a funny state, and Go is just doing what Unicode says. Lowercasing and uppercasing tends to canonicalize.
<br>The ess-zed character is different but similar. It's U+1e9e and lowercases to U+00DF, but that uppercases to a plain 'S', U+0053.
<br>So although it may be surprising behavior, it's correct.
<br>By the way, case changing is not reflexive, however it may seem it should be. The rules aren't even consistent for the same code point in different languages.
