### ISSUE TITLE
How to generate a Go parameter name?

### ISSUE THREAD

**Issue by MartyHub** [chanced/caps#29]
Hello,

I'm using `caps` to generate some Go code and I was wondering if there was a way to achieve the following behavior:
```go
caps.ToLowerCamel("entity id") // entityID
caps.ToLowerCamel("id") // id
```

Actually, the second example generates "ID"
And if I use the `caps.WithReplaceStyleLower()` option, the first example is not right anymore

Thanks and regards

**Comment by chanced** [comment]
Hmm, that's definitely a bug. The second should have been `"id"` as well..

I'll fix it but in the meantime, this works:

```go
caps.ToLowerCamel("entity id")                        // entityID
caps.ToLowerCamel("id", caps.WithReplaceStyleLower()) // id
```
https://go.dev/play/p/K5r_72rYHDx

Thank you for reporting it.

**Comment by chanced** [comment]
Oh wait, I see what your problem is. If you use `WithReplaceStyleLower` then the first wouldn't be correct.

**Comment by chanced** [comment]
I released version `1.0.1` which should fix this. Sorry about that.

**Comment by MartyHub** [comment]
It's working great, thank you!

**Comment by chanced** [comment]
Awesome, glad to hear it!
